name: .NET Build

on:
  workflow_call:

jobs:
  build:
    name: Build dotnet project
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Install Wix
      uses: actions/checkout@v3
      with:
        repository: fbarresi/wix
        path: wix

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build vs/vs.csproj --no-restore

    - name: Build Installer
      run: |
        wix\tools\candle.exe vs.install\Product.wxs -o obj\ -ext WixUtilExtension
        wix\tools\light.exe obj\*.wixobj -o bin\vs.install.msi -ext WixUtilExtension""
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with: 
        name: Installer Msi
        path: bin\vs.install.msi
